[theme]

# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
# base =

# Primary accent color for interactive elements.
# primaryColor =

# Background color for the main content area.
backgroundColor="#FFFFFF"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor="#E7F8FF"

# Color used for almost all text.
# textColor =

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
# font =

[server]
# Default: 200
maxUploadSize = 1